[package]
name = "yasl"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
env_logger = "0.11.11"
log = "0.4"
chrono = "0.4"
tabular = "0.2.0"
quick_cache = "0.7.0"
discord-webhook-lib = "0.2.3"
signal-hook = "0.4.0"
futures = "0.3"

[dependencies.signal-hook-tokio]
version = "0.4"
features = ["futures-v0_3"]

[dependencies.ohno]
version = "0.4"
features = ["app-err"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.figment2]
version = "0.11.5"
features = ["toml"]

[dependencies.poise]
git = "https://github.com/serenity-rs/poise"
branch = "next"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"

[dependencies.tokio]
version = "1.53.1"
features = ["full"]

[dependencies.sqlx]
version = "0.8.6"
features = [
    "sqlx-sqlite",
    "sqlite",
    "runtime-tokio",
    "derive",
    "tls-rustls-ring-webpki",
]


[build-dependencies]
built = "0.8.1"
